### ISSUE TITLE
Apparent Virus

### ISSUE THREAD

**Issue by Gman-TX** [stokie-ant/lcdsmartie-laz#16]
Had some problems with the latest download.
![Screenshot 2023-07-15 175148](https://github.com/stokie-ant/lcdsmartie-laz/assets/13007268/3581bc13-d0e6-4a5b-84af-99d8bb08eda5)
![Screenshot 2023-07-15 175635](https://github.com/stokie-ant/lcdsmartie-laz/assets/13007268/63e6dbf1-c262-4bbf-80da-9afa1681955a)

**Comment by stokie-ant** [comment]
Is this windows 11 defender?
I haven't had any issue personally but I'll try to submit the file for analysis.
Possibly triggered by the way the program behaves as a shim between LCDSmartie and the dll with no user interface

**Comment by limbo666** [comment]
VirusTotal gives a 20/71 positive score on "LegacyLoader.exe"  
maybe the report on the page can explain what was the cause of this:
https://www.virustotal.com/gui/file/dba966688cce2935a8c27087836fe67efee131a2737fd935113b91a465cca857?nocache=1

**Comment by stokie-ant** [comment]
Yeah, I did check that last night but there's no useful information as its not flagged by the sandboxes.
I did a recompile and windows defender actually flagged the debug output file but changing a few options I was able to prevent that and bring the virustotal detection to 14
[https://www.virustotal.com/gui/file/c6d51ffb6de03599b8c902092cc457cc86bdf5e35586c38e1f34a157242abb1c?nocache=1](https://www.virustotal.com/gui/file/c6d51ffb6de03599b8c902092cc457cc86bdf5e35586c38e1f34a157242abb1c?nocache=1)

Most of it is caused by having no GUI as adding one even though hidden brings it down to 2
[https://www.virustotal.com/gui/file/55ae21af17d1693f556f7776321830e6e11374908eb2349bfaecacd41b12b0d4?nocache=1](https://www.virustotal.com/gui/file/55ae21af17d1693f556f7776321830e6e11374908eb2349bfaecacd41b12b0d4?nocache=1)
But that increases the file size by 800% unnecessarily

**Comment by Gman-TX** [comment]
Yes, Windows 11 defender.  Previously using Just started using this OS due to my Win8 pc getting constant notifications about it being dated.  Loaded Win10, but jumped to WIn11 quickly due to a laptop I switched and liked the improvements overall.  Thank you for your explanation and efforts at maintaining/improving this code.
